{
 "title": "Latencies",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "2h",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\", job=\"prometheus\"} - node_memory_MemFree_bytes{instance=\"node-exporter:9100\", job=\"prometheus\"} - node_memory_Cached_bytes{instance=\"node-exporter:9100\", job=\"prometheus\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"node-exporter:9100\", job=\"prometheus\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"node-exporter:9100\", job=\"prometheus\"}",
     "legendFormat": "Cached"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Latency per connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "tcp_connlat_msec", "legendFormat": "{{daddr}}" }
   ]
  },
  {
   "title": "Average latency [ms]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(tcp_connlat_msec)", "legendFormat": "Average Latency" }
   ]
  }
 ]
}