global:
  scrape_interval: 1s
  # scrape_timeout: 1s
  evaluation_interval: 1s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 2s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 1s
  # scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['localhost:9090', 'node-exporter:9100', 'host.docker.internal:9435', 'host.docker.internal:9091']